---
collections:
  - name: community.general
  - name: community.docker
  - name: ansible.windows
  - name: community.windows
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.netcommon
