---
# Wazuh Manager - API Configuration

- name: Configure Wazuh API settings
  ansible.builtin.template:
    src: api.yaml.j2
    dest: "{{ wazuh_manager_install_path }}/api/configuration/api.yaml"
    owner: "{{ wazuh_manager_owner }}"
    group: "{{ wazuh_manager_group }}"
    mode: '0640'
  become: true
  no_log: true
  notify: restart wazuh-manager

- name: Configure API SSL certificates directory
  ansible.builtin.file:
    path: "{{ wazuh_manager_install_path }}/api/configuration/ssl"
    state: directory
    owner: "{{ wazuh_manager_owner }}"
    group: "{{ wazuh_manager_group }}"
    mode: '0750'
  become: true

- name: Copy API SSL certificate
  ansible.builtin.copy:
    src: "{{ wazuh_manager_certs_path }}/{{ wazuh_manager_cert_name }}.pem"
    dest: "{{ wazuh_manager_install_path }}/api/configuration/ssl/server.crt"
    remote_src: true
    owner: "{{ wazuh_manager_owner }}"
    group: "{{ wazuh_manager_group }}"
    mode: '0400'
  become: true
  notify: restart wazuh-manager

- name: Copy API SSL private key
  ansible.builtin.copy:
    src: "{{ wazuh_manager_certs_path }}/{{ wazuh_manager_cert_name }}-key.pem"
    dest: "{{ wazuh_manager_install_path }}/api/configuration/ssl/server.key"
    remote_src: true
    owner: "{{ wazuh_manager_owner }}"
    group: "{{ wazuh_manager_group }}"
    mode: '0400'
  become: true
  notify: restart wazuh-manager
