---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml

driver:
  name: docker

platforms:
  - name: wazuh-monitoring
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd

provisioner:
  name: ansible
  inventory:
    links:
      - source: hosts.yml
    group_vars:
      all:
        wazuh_version: "4.14.5"
        wazuh_indexer_admin_password: "TestPass1234@"
        wazuh_api_password: "TestPass1234@"
        wazuh_manager_cluster_key: "abc123def456abc123def456abc12345"
        wazuh_indexer_nodes:
          - name: indexer-1
            ip: 127.0.0.1
        wazuh_manager_nodes:
          - name: manager-1
            ip: 127.0.0.1
        wazuh_ssl_verify_certificates: false
        wazuh_configure_firewall: false
        wazuh_monitoring_enabled: true
        wazuh_indexer_exporter_enabled: true
        wazuh_manager_exporter_enabled: true
        wazuh_grafana_dashboard_enabled: false

verifier:
  name: ansible
