---
# Wazuh Manager - Handlers

- name: restart wazuh-manager
  ansible.builtin.systemd:
    name: "{{ wazuh_manager_service_name }}"
    state: restarted
    no_block: true
  become: true

- name: reload wazuh-manager
  ansible.builtin.systemd:
    name: "{{ wazuh_manager_service_name }}"
    state: reloaded
  become: true

- name: reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  become: true

- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    no_block: true
  become: true
