---
# Wazuh Monitoring Role - Handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart opensearch exporter
  ansible.builtin.systemd:
    name: wazuh-opensearch-exporter
    state: restarted

- name: Restart wazuh manager exporter
  ansible.builtin.systemd:
    name: wazuh-manager-exporter
    state: restarted

- name: Restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
  when: wazuh_monitoring_grafana_enabled | default(true) | bool
