#!/bin/bash
# Wazuh Deployment - Post-Deployment User Lockdown
# This script restricts the ansible deployment user after deployment completes
# Run this on target hosts to secure the deployment user when not in use

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
ANSIBLE_USER="${ANSIBLE_USER:-wazuh-deploy}"
UNLOCK_SCRIPT="/usr/local/bin/wazuh-unlock-deploy"

print_info() { echo -e "${YELLOW}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[OK]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    print_error "This script must be run as root"
    exit 1
fi

# Verify user exists
if ! id "$ANSIBLE_USER" &>/dev/null; then
    print_error "User $ANSIBLE_USER does not exist"
    exit 1
fi

print_info "Locking down user: $ANSIBLE_USER"

# Create the unlock script that the user can run to restore access
cat > "$UNLOCK_SCRIPT" << 'UNLOCKEOF'
#!/bin/bash
# Wazuh Deployment - Unlock Script
# Restores full sudo access to the ansible deployment user
# This script can be run by the locked-down user via restricted sudo

set -euo pipefail

ANSIBLE_USER="${SUDO_USER:-wazuh-deploy}"
SUDOERS_FILE="/etc/sudoers.d/${ANSIBLE_USER}"
LOCK_FLAG="/var/lib/wazuh-deploy/.locked"

# Verify we're being run correctly
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run with sudo"
    exit 1
fi

# Restore full sudo access
echo "${ANSIBLE_USER} ALL=(ALL) NOPASSWD: ALL" > "$SUDOERS_FILE"
chmod 440 "$SUDOERS_FILE"

# Validate sudoers syntax
if ! visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
    echo "ERROR: Invalid sudoers syntax"
    exit 1
fi

# Remove lock flag
rm -f "$LOCK_FLAG"

# Log the unlock
logger -t wazuh-deploy "Ansible deployment user $ANSIBLE_USER unlocked by $(whoami)"

echo "Deployment user $ANSIBLE_USER has been unlocked"
echo "Full sudo access has been restored"
echo "Remember to run lockdown after deployment completes"
UNLOCKEOF

chmod 755 "$UNLOCK_SCRIPT"
chown root:root "$UNLOCK_SCRIPT"

# Create restricted sudoers file that only allows:
# 1. Running the unlock script
# 2. Basic system checks (for ansible ping/facts)
# 3. Reading wazuh status
SUDOERS_FILE="/etc/sudoers.d/${ANSIBLE_USER}"

cat > "$SUDOERS_FILE" << EOF
# Wazuh Ansible deployment user - LOCKED DOWN
# Generated by lockdown-ansible-user.sh on $(date)
# Run 'sudo $UNLOCK_SCRIPT' to restore full access before next deployment

# Allow unlocking for next deployment
${ANSIBLE_USER} ALL=(ALL) NOPASSWD: ${UNLOCK_SCRIPT}

# Allow basic Ansible connectivity checks (gather_facts)
${ANSIBLE_USER} ALL=(ALL) NOPASSWD: /usr/bin/python3, /usr/bin/python
${ANSIBLE_USER} ALL=(ALL) NOPASSWD: /bin/sh -c echo*

# Allow checking Wazuh service status (read-only)
${ANSIBLE_USER} ALL=(ALL) NOPASSWD: /usr/bin/systemctl status wazuh-*
${ANSIBLE_USER} ALL=(ALL) NOPASSWD: /usr/bin/systemctl is-active wazuh-*
${ANSIBLE_USER} ALL=(ALL) NOPASSWD: /var/ossec/bin/wazuh-control status
${ANSIBLE_USER} ALL=(ALL) NOPASSWD: /var/ossec/bin/agent_control -l

# Deny everything else (implicit, but explicit for clarity)
# All other sudo commands will prompt for password (which isn't set)
EOF

chmod 440 "$SUDOERS_FILE"

# Validate sudoers syntax
if ! visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
    print_error "Invalid sudoers syntax - restoring full access"
    echo "${ANSIBLE_USER} ALL=(ALL) NOPASSWD: ALL" > "$SUDOERS_FILE"
    chmod 440 "$SUDOERS_FILE"
    exit 1
fi

# Create lock flag directory and file
mkdir -p /var/lib/wazuh-deploy
touch /var/lib/wazuh-deploy/.locked
chown root:root /var/lib/wazuh-deploy/.locked
chmod 644 /var/lib/wazuh-deploy/.locked

# Optionally lock the user account (disable password login)
# Uncomment to also disable SSH key access until unlocked
# passwd -l "$ANSIBLE_USER"

# Log the lockdown
logger -t wazuh-deploy "Ansible deployment user $ANSIBLE_USER locked down"

print_success "User $ANSIBLE_USER has been locked down"
print_info "Restricted to: unlock script, Ansible facts, Wazuh status checks"
print_info ""
print_info "To restore access before next deployment, run:"
print_info "  ssh $ANSIBLE_USER@<host> 'sudo $UNLOCK_SCRIPT'"
print_info ""
print_info "Or use the unlock playbook:"
print_info "  ansible-playbook unlock-deploy-user.yml"
