#!/bin/bash

# Wazuh Deployment - Ansible Vault Management Script
# Manages encrypted credentials for secure deployment

set -euo pipefail

# Ensure plaintext temp files are securely shredded on exit/interrupt
# shred -u overwrites before unlinking to prevent disk-recovery of secrets
trap 'shred -u "${VAULT_FILE:-}.tmp" "${VAULT_PASSWORD_FILE:-}.new" 2>/dev/null; rm -f "${VAULT_FILE:-}.tmp" "${VAULT_PASSWORD_FILE:-}.new"' EXIT INT TERM

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
source "$PROJECT_DIR/lib/generators.sh"
# Use group_vars/all/ directory structure for proper Ansible auto-loading
VAULT_DIR="$PROJECT_DIR/group_vars/all"
VAULT_FILE="$VAULT_DIR/vault.yml"
VAULT_PASSWORD_DIR="${HOME}/.config/wazuh-deployment"
VAULT_PASSWORD_FILE="$VAULT_PASSWORD_DIR/.vault_password"
# Credentials stored exclusively in Ansible Vault — no plaintext files on disk

print_header() {
    echo -e "\n${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  $1${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

# generate_yaml_safe_password is provided by lib/generators.sh (sourced above)

# Initialize vault with a new password
init_vault() {
    print_header "Initializing Ansible Vault"

    if [ -f "$VAULT_PASSWORD_FILE" ]; then
        print_warning "Vault password file already exists: $VAULT_PASSWORD_FILE"
        read -p "Overwrite existing vault password? (y/N): " overwrite
        if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
            print_info "Keeping existing vault password"
            return 0
        fi
    fi

    # Generate vault password
    local vault_password=$(generate_yaml_safe_password 32)
    mkdir -p "$VAULT_PASSWORD_DIR"
    echo "$vault_password" > "$VAULT_PASSWORD_FILE"
    chmod 600 "$VAULT_PASSWORD_FILE"

    print_success "Vault password generated and saved to: $VAULT_PASSWORD_FILE"
    print_warning "IMPORTANT: Back up this file securely! Without it, you cannot decrypt your credentials."

    # Add to .gitignore if not already there
    if ! grep -q ".vault_password" "$PROJECT_DIR/.gitignore" 2>/dev/null; then
        echo ".vault_password" >> "$PROJECT_DIR/.gitignore"
        print_info "Added .vault_password to .gitignore"
    fi
}

# Create or update vault file with credentials.
# Preferred: pass --creds-file <path> (mode-0600 key=value file) to avoid
# leaking secrets via /proc/<pid>/environ.
# Fallback: reads VAULT_* environment variables when no --creds-file is given.
#   VAULT_INDEXER_PASSWORD, VAULT_API_PASSWORD, VAULT_ENROLLMENT_PASSWORD
#   VAULT_DASHBOARD_ADMIN_PASSWORD, VAULT_GRAFANA_API_KEY
#   VAULT_ANSIBLE_USER, VAULT_CONNECTION_PASSWORD, VAULT_BECOME_PASSWORD
#   VAULT_HOST_CREDENTIALS (format: "host1:user1:pass1,host2:user2:pass2")
#   VAULT_CLUSTER_KEY
create_vault() {
    local creds_file=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --creds-file)
                creds_file="$2"
                shift 2
                ;;
            *)
                print_error "Unknown argument: $1"
                exit 1
                ;;
        esac
    done

    if [[ -n "$creds_file" ]]; then
        if [[ ! -f "$creds_file" ]]; then
            print_error "Creds file not found: $creds_file"
            exit 1
        fi
        # Source the key=value pairs into the environment of this function only
        local line key value
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            key="${line%%=*}"
            value="${line#*=}"
            # Allow only expected VAULT_* keys to prevent arbitrary code injection
            case "$key" in
                VAULT_INDEXER_PASSWORD|VAULT_API_PASSWORD|VAULT_ENROLLMENT_PASSWORD|\
                VAULT_ANSIBLE_USER|VAULT_CONNECTION_PASSWORD|VAULT_BECOME_PASSWORD|\
                VAULT_HOST_CREDENTIALS|VAULT_CLUSTER_KEY|VAULT_FILEBEAT_PASSWORD)
                    printf -v "$key" '%s' "$value"
                    ;;
                *)
                    print_error "Unexpected key in creds file: $key"
                    exit 1
                    ;;
            esac
        done < "$creds_file"
    fi
    print_header "Creating Encrypted Vault"

    if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
        print_error "Vault password file not found. Run: $0 init"
        exit 1
    fi

    mkdir -p "$VAULT_DIR"

    # Escape double-quotes in user-supplied values to prevent YAML scalar breakout.
    # Passwords generated by generate_yaml_safe_password never contain " so this
    # is only needed for the env-var path where the caller controls the value.
    sanitize_for_yaml() { printf '%s' "${1//\"/\\\"}"; }

    # Use environment variables if set, otherwise generate new passwords
    local indexer_password="${VAULT_INDEXER_PASSWORD:-}"
    local api_password="${VAULT_API_PASSWORD:-}"
    local enrollment_password="${VAULT_ENROLLMENT_PASSWORD:-}"
    local connection_password="${VAULT_CONNECTION_PASSWORD:-}"
    local become_password="${VAULT_BECOME_PASSWORD:-}"
    local ansible_user="${VAULT_ANSIBLE_USER:-wazuh-deploy}"
    local cluster_key="${VAULT_CLUSTER_KEY:-}"
    local dashboard_admin_password="${VAULT_DASHBOARD_ADMIN_PASSWORD:-}"
    local grafana_api_key="${VAULT_GRAFANA_API_KEY:-}"
    local filebeat_password="${VAULT_FILEBEAT_PASSWORD:-}"

    # Generate passwords if not provided
    if [ -z "$indexer_password" ]; then
        indexer_password=$(generate_yaml_safe_password 24)
        print_info "Generated new indexer admin password"
    fi

    if [ -z "$api_password" ]; then
        api_password=$(generate_yaml_safe_password 24)
        print_info "Generated new API password"
    fi

    if [ -z "$enrollment_password" ]; then
        enrollment_password=$(generate_yaml_safe_password 24)
        print_info "Generated new agent enrollment password"
    fi

    if [ -z "$filebeat_password" ]; then
        filebeat_password=$(generate_yaml_safe_password 24)
    fi

    if [ -z "$cluster_key" ]; then
        cluster_key=$(generate_yaml_safe_password 32)
    fi

    if [ -z "$dashboard_admin_password" ]; then
        dashboard_admin_password=$(generate_yaml_safe_password 24)
    fi

    if [ -z "$grafana_api_key" ]; then
        grafana_api_key=$(generate_yaml_safe_password 32)
    fi

    # Sanitize externally-supplied values before YAML interpolation
    [ -n "$indexer_password" ]    && indexer_password=$(sanitize_for_yaml "$indexer_password")
    [ -n "$api_password" ]        && api_password=$(sanitize_for_yaml "$api_password")
    [ -n "$enrollment_password" ] && enrollment_password=$(sanitize_for_yaml "$enrollment_password")
    [ -n "$connection_password" ]     && connection_password=$(sanitize_for_yaml "$connection_password")
    [ -n "$become_password" ]         && become_password=$(sanitize_for_yaml "$become_password")
    [ -n "$dashboard_admin_password" ] && dashboard_admin_password=$(sanitize_for_yaml "$dashboard_admin_password")
    [ -n "$grafana_api_key" ]         && grafana_api_key=$(sanitize_for_yaml "$grafana_api_key")

    # Build per-host SSH credentials content
    local host_creds_content=""
    if [ -n "${VAULT_HOST_CREDENTIALS:-}" ]; then
        print_info "Processing per-host SSH credentials"
        IFS=',' read -ra HOST_ENTRIES <<< "$VAULT_HOST_CREDENTIALS"
        for entry in "${HOST_ENTRIES[@]}"; do
            IFS=':' read -r host user pass <<< "$entry"
            if [ -n "$host" ]; then
                local safe_host="${host//./_}"
                # Store username for this host
                if [ -n "$user" ]; then
                    local escaped_user
                    escaped_user="$(yaml_escape "$user")" || exit 1
                    host_creds_content+="
# SSH user for host: ${host}
vault_ssh_user_${safe_host}: \"${escaped_user}\""
                fi
                # Store password for this host
                if [ -n "$pass" ]; then
                    local escaped_pass
                    escaped_pass="$(yaml_escape "$pass")" || exit 1
                    host_creds_content+="
# SSH password for host: ${host}
vault_ssh_pass_${safe_host}: \"${escaped_pass}\""
                fi
            fi
        done
    fi

    # Escape all operator-supplied values before YAML interpolation
    local e_ansible_user e_connection_password e_become_password
    local e_indexer_password e_api_password e_enrollment_password e_cluster_key e_filebeat_password
    e_ansible_user="$(yaml_escape "$ansible_user")"           || exit 1
    e_connection_password="$(yaml_escape "$connection_password")" || exit 1
    e_become_password="$(yaml_escape "$become_password")"     || exit 1
    e_indexer_password="$(yaml_escape "$indexer_password")"   || exit 1
    e_api_password="$(yaml_escape "$api_password")"           || exit 1
    e_enrollment_password="$(yaml_escape "$enrollment_password")" || exit 1
    e_cluster_key="$(yaml_escape "$cluster_key")"             || exit 1
    e_filebeat_password="$(yaml_escape "$filebeat_password")" || exit 1

    # Create vault content
    local vault_content="---
# Wazuh Deployment - Encrypted Credentials
# Generated: $(date -Iseconds)
# DO NOT COMMIT THIS FILE UNENCRYPTED!

# Ansible SSH user for deployment
vault_ansible_user: \"${e_ansible_user}\"

# Ansible connection password (SSH/WinRM) - default for all hosts
vault_ansible_connection_password: \"${e_connection_password}\"

# Ansible become (sudo) password
vault_ansible_become_password: \"${e_become_password}\"
${host_creds_content}

# Indexer/Dashboard admin credentials
vault_wazuh_indexer_admin_password: \"${e_indexer_password}\"

# Wazuh API credentials
vault_wazuh_api_password: \"${e_api_password}\"

# Agent enrollment password
vault_wazuh_agent_enrollment_password: \"${e_enrollment_password}\"

# Manager cluster key (for multi-node deployments)
vault_wazuh_manager_cluster_key: \"${cluster_key}\"

# Dashboard admin password (if different from indexer admin; leave empty to reuse indexer admin)
vault_wazuh_dashboard_admin_password: \"${dashboard_admin_password}\"

# Grafana API key (for monitoring dashboard)
vault_grafana_api_key: \"${grafana_api_key}\"
"

    # Write and encrypt
    (umask 077; echo "$vault_content" > "${VAULT_FILE}.tmp")
    ANSIBLE_VAULT_PASSWORD_FILE="$VAULT_PASSWORD_FILE" \
      ansible-vault encrypt "${VAULT_FILE}.tmp" --encrypt-vault-id default --output "$VAULT_FILE"
    shred -u "${VAULT_FILE}.tmp" 2>/dev/null || rm -f "${VAULT_FILE}.tmp"
    chmod 600 "$VAULT_FILE"

    print_success "Encrypted vault created: $VAULT_FILE"
}

# View vault contents (decrypted)
view_vault() {
    print_header "Vault Contents"

    if [ ! -f "$VAULT_FILE" ]; then
        print_error "Vault file not found: $VAULT_FILE"
        exit 1
    fi

    if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
        print_error "Vault password file not found: $VAULT_PASSWORD_FILE"
        exit 1
    fi

    ANSIBLE_VAULT_PASSWORD_FILE="$VAULT_PASSWORD_FILE" ansible-vault view "$VAULT_FILE"
}

# Edit vault contents
edit_vault() {
    print_header "Editing Vault"

    if [ ! -f "$VAULT_FILE" ]; then
        print_error "Vault file not found. Run: $0 create"
        exit 1
    fi

    if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
        print_error "Vault password file not found: $VAULT_PASSWORD_FILE"
        exit 1
    fi

    ANSIBLE_VAULT_PASSWORD_FILE="$VAULT_PASSWORD_FILE" ansible-vault edit "$VAULT_FILE"
    print_success "Vault updated"
}

# Rotate all credentials
rotate_credentials() {
    print_header "Rotating Credentials"

    if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
        print_error "Vault password file not found. Run: $0 init"
        exit 1
    fi

    # Backup existing vault
    if [ -f "$VAULT_FILE" ]; then
        cp "$VAULT_FILE" "${VAULT_FILE}.backup.$(date +%Y%m%d%H%M%S)"
        print_info "Backed up existing vault"
    fi

    # Create new vault with new credentials
    create_vault

    print_success "Credentials rotated successfully"
    print_warning "Remember to redeploy to apply new credentials: ansible-playbook site.yml"
}

# Rekey vault (change vault password)
rekey_vault() {
    print_header "Rekeying Vault"

    if [ ! -f "$VAULT_FILE" ]; then
        print_error "Vault file not found: $VAULT_FILE"
        exit 1
    fi

    if [ ! -f "$VAULT_PASSWORD_FILE" ]; then
        print_error "Current vault password file not found: $VAULT_PASSWORD_FILE"
        exit 1
    fi

    # Generate new vault password
    local new_password=$(generate_yaml_safe_password 32)
    local new_password_file="${VAULT_PASSWORD_FILE}.new"
    echo "$new_password" > "$new_password_file"

    # Rekey the vault
    ANSIBLE_VAULT_PASSWORD_FILE="$VAULT_PASSWORD_FILE" \
      ansible-vault rekey "$VAULT_FILE" \
        --new-vault-password-file "$new_password_file"

    # Replace old password file with shred cleanup
    shred -u "$VAULT_PASSWORD_FILE" 2>/dev/null || rm -f "$VAULT_PASSWORD_FILE"
    mv "$new_password_file" "$VAULT_PASSWORD_FILE"
    chmod 600 "$VAULT_PASSWORD_FILE"

    print_success "Vault rekeyed with new password"
    print_warning "IMPORTANT: Back up the new vault password file!"
}

# Show usage
usage() {
    echo "Wazuh Deployment - Ansible Vault Manager"
    echo ""
    echo "Usage: $0 <command>"
    echo ""
    echo "Commands:"
    echo "  init      Initialize vault with a new password"
    echo "  create    Create encrypted vault with credentials"
    echo "  view      View vault contents (decrypted)"
    echo "  edit      Edit vault contents"
    echo "  rotate    Rotate all credentials"
    echo "  rekey     Change vault password"
    echo ""
    echo "Examples:"
    echo "  $0 init      # First-time setup"
    echo "  $0 create    # Generate and encrypt credentials"
    echo "  $0 view      # Show current credentials"
    echo "  $0 rotate    # Generate new credentials"
    echo ""
    echo "Files:"
    echo "  Vault file:     $VAULT_FILE"
    echo "  Password file:  $VAULT_PASSWORD_FILE"
    echo "  Credentials:    (stored encrypted in Ansible Vault only)"
}

# Main
case "${1:-}" in
    init)
        init_vault
        ;;
    create)
        shift
        create_vault "$@"
        ;;
    view)
        view_vault
        ;;
    edit)
        edit_vault
        ;;
    rotate)
        rotate_credentials
        ;;
    rekey)
        rekey_vault
        ;;
    *)
        usage
        exit 1
        ;;
esac
